# Generated by Django 5.2.3 on 2025-07-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
